# Javascript Node  CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/repo
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v9-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Top Deps
          command: npm install
      - run:
          name: Install Sub Packages Deps
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: cache-v9-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./packages/*/node_modules
            - ./packages/*/lib
  test_api_integration:
    working_directory: /home/circleci/repo
    docker:
      - image: circleci/node:10.13.0
      - image: circleci/mongo:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v9-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Top Deps
          command: npm install
      - run:
          name: Install Sub Packages Deps
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run API Integration
          command: npm run ci:api
  test_ui_integration:
    working_directory: /root/repo
    docker:
      - image: cypress/base:10
      - image: circleci/mongo:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-cy2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Check if package-lock.json exists
          command: |
            if [ ! -e ./package-lock.json ]; then
              echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
              echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
              echo "and commit 'package-lock.json' to your repo."
              exit 1
            fi
      - run:
          name: Install Top Deps
          command: npm install
      - run:
          name: Install Sub Packages Deps
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build
      - run:
          name: Verfy Cypress
          command: npm run cy:verify
      - run:
          name: Run UI Integration
          command: npm run ci:ui
      - save_cache:
          key: cache-cy2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - /root/.npm
            - /root/.cache
      - persist_to_workspace:
          root: /root
          paths:
            - repo
            - .cache/Cypress
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_api_integration:
          requires:
            - build
      - test_ui_integration:
          requires:
            - build
