# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  do-everything:
    docker:
      - image: circleci/node:10.13.0
#      - image: cypress/base:10
      - image: circleci/mongo:3.6
    parallelism: 1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v3-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Top Deps
          command: npm install
      - run:
          name: Install Sub Packages Deps
          command: npm run bootstrap
#      - run:
#          name: Verify Cypress
#          command: npm run cy:verify
      - save_cache:
          key: cache-v3-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - node_modules
#      - persist_to_workspace:
#          root: ~/
#          paths:
#            - .cache/Cypress
#      - attach_workspace:
#          at: ~/
      - run:
          name: Run API Integration
          command: npm run ci:api
#      - run:
#          name: Run UI Integration
#          command: npm run ci:ui
workflows:
  version: 2
  build_and_test:
    jobs:
      - do-everything
